# Generated by Django 3.0.6 on 2020-05-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.IntegerField()),
                ('ip', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
            ],
        ),
    ]
